remote_theme: baagaard-usgs/just-the-docs
title: CenCalVM
baseurl: /earthquake-cencalvm
#search_enabled: true
aux_links:
    "GitHub repository":
      - "//github.com/usgs/earthquake-cencalvm"

color_scheme: usgs_lightbg
heading_anchors: false
search_enabled: true

title_image: images/USGSsimple.png
software_version: 1.1.0
